### PR TITLE
Fixed logging to stdout

### PR DESCRIPTION
**Pull request by schmaddi**
Due to the change in the logging framework in jamf pro, the configuration file for Log4j has been changed.

### CODE REVIEW

**Comment by schmaddi** [comment]
Jamf Pro - Version 10.31.0

**Comment by battlecow** [comment]
nice! 👍  My preference here would be to add a file check around the replacements to ensure backwards compatibility.

**Comment by schmaddi** [comment]
> 
> 
> nice! 👍 My preference here would be to add a file check around the replacements to ensure backwards compatibility.

Done :)

**Comment by ahousseini** [comment]
I have created another approach with `xmlstarlet` if anyone is interested:

```
xmlstarlet \
  edit --inplace --subnode "/Configuration/Appenders" --type elem -n "ConsoleTMP" --value "" \
  --insert ///ConsoleTMP --type attr -n "name" --value "Console" \
  --insert ///ConsoleTMP --type attr -n "target" --value "SYSTEM_OUT" \
  --rename ///ConsoleTMP -v Console \
  "/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/log4j2.xml"

xmlstarlet \
  edit --inplace --subnode "/Configuration/Appenders/Console" --type elem -n "PatternLayoutTMP" --value "" \
  --insert ////PatternLayoutTMP --type attr -n "pattern" --value "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n" \
  --rename ////PatternLayoutTMP -v PatternLayoutTMP \
  "/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/log4j2.xml"

xmlstarlet \
  edit --inplace --subnode "/Configuration/Loggers/Logger[@name='com.jamfsoftware.analytics.file']" --type elem -n "AppenderRefTMP" --value "" \
  --insert ////AppenderRefTMP --type attr -n "ref" --value "Console" \
  --rename ////AppenderRefTMP -v AppenderRef \
  "/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/log4j2.xml"

xmlstarlet \
  edit --inplace --subnode "/Configuration/Loggers/Logger[@name='com.jamfsoftware.vpp']" --type elem -n "AppenderRefTMP" --value "" \
  --insert ////AppenderRefTMP --type attr -n "ref" --value "Console" \
  --rename ////AppenderRefTMP -v AppenderRef \
  "/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/log4j2.xml"

xmlstarlet \
  edit --inplace --subnode "/Configuration/Loggers/Root" --type elem -n "AppenderRefTMP" --value "" \
  --insert ////AppenderRefTMP --type attr -n "ref" --value "Console" \
  --rename ////AppenderRefTMP -v AppenderRef \
  "/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/log4j2.xml"
```

**Review by battlecow — APPROVED** [review]
LGTM

**Pull request merged**
